# --- !Ups

CREATE TABLE USERS (
  ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(254) NOT NULL,
  PASSWORD VARCHAR(254),
  UNIQUE(NAME)
) AUTO_INCREMENT=0;

INSERT INTO USERS
   (NAME, PASSWORD)
VALUES
   ('Admin', 'Admin'),
   ('MissA', 'A'),
   ('MisterB', 'B');

# --- !Downs

DROP TABLE IF EXISTS USERS;