CREATE DATABASE IF NOT EXISTS finance;
GRANT ALL PRIVILEGES ON finance.* TO 'finance'@'localhost' IDENTIFIED BY 'gecko';
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS financeTest;
GRANT ALL PRIVILEGES ON financeTest.* TO 'financeTest'@'localhost' IDENTIFIED BY 'geckoTest';
FLUSH PRIVILEGES;