# --- !Ups

INSERT INTO USERS(NAME, PASSWORD) VALUES('Me', 'Me');
INSERT INTO USERS(NAME, PASSWORD) VALUES('Spouse', 'Spouse');

# --- !Downs

DELETE FROM USERS WHERE NAME='Me';
DELETE FROM USERS WHERE NAME='Spouse';