CREATE TABLE COFFEES (
  COF_NAME varchar(254) NOT NULL,
  SUP_ID int(11) NOT NULL,
  PRICE double NOT NULL,
  SALES int(11) NOT NULL,
  TOTAL int(11) NOT NULL,
  PRIMARY KEY (COF_NAME),
  KEY SUP_FK (SUP_ID),
  CONSTRAINT SUP_FK FOREIGN KEY (SUP_ID) REFERENCES SUPPLIERS (SUP_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);