CREATE TABLE HOLDINGS (
  FUND_ID BIGINT NOT NULL,
  USER_ID BIGINT NOT NULL,
  UNITS DOUBLE NOT NULL,
  HOLDING_DATE DATE NOT NULL,
  PRIMARY KEY (FUND_ID, USER_ID, HOLDING_DATE),
  CONSTRAINT HOLDINGS_FUND_FK FOREIGN KEY (FUND_ID) REFERENCES FUNDS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT HOLDINGS_USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);
