CREATE TABLE PRICES (
  FUND_ID BIGINT NOT NULL,
  PRICE_DATE DATE NOT NULL,
  PRICE DOUBLE NOT NULL,
  PRIMARY KEY (FUND_ID, PRICE_DATE),
  CONSTRAINT PRICES_FUND_FK FOREIGN KEY (FUND_ID) REFERENCES FUNDS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);